### ISSUE TITLE
No module named boto3

### ISSUE THREAD

**Issue by demon86rm** [RedHatTraining/AI26X-apps#13]
I ran into this error:
![image](https://github.com/RedHatTraining/AI26X-apps/assets/48250561/dcdf2e19-60dd-4830-b50e-e57b72234cfe)

In my case, to make the notebook working I had to run a cell with `%pip install boto3` just before the `import` block, then the notebook execution was flawless.

**Comment by demon86rm** [comment]
Opened [pull request #14 ](https://github.com/RedHatTraining/AI26X-apps/pull/14) for this.

**Comment by gjbianco** [comment]
Hey there, thanks for the submission!

Which workbench image did you use when you ran into this? It looks like the package is already installed in the `Standard Data Science` image.

**Comment by demon86rm** [comment]
Hi, I think I ran the exercise following the guidelines, but I'm not sure about the image I've used. I'll rerun it and get back to you as soon as possible

**Comment by demon86rm** [comment]
Hi Guy, 

you were absolutely right, I've probably mis-clicked the image and used another one instead of the `Standard Data Science`.
Sorry for bothering, yesterday I was too swifty and I've also opened MR #14 for this so ignore that and I'll manage to cancel it.
